# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
minimal_mistakes_skin: "aqua" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
remote_theme: "mmistakes/minimal-mistakes"

# Site Settings
locale: "en-US"
title: "V-Lumin"
title_separator: "-"
name: "V-Lumin"
description: "Your Trusted Expert in Fiber Optic Solutions"
url: "[invalid url, do not cite]
baseurl: ""
repository: "Hsunfrank/Hsunfrank.github.io"
teaser: # path of fallback teaser image, e.g., "/assets/images/500x300.png"
logo: # path of logo image, e.g., "/assets/images/88x88.png"
masthead_title: # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs: false
words_per_minute: 200
copyright: "© 2025 V-Lumin"
copyright_url: "[invalid url, do not cite]
timezone: "Asia/Shanghai"
comments:
  provider: false # Disable comments
atom_feed:
  hide: true # Hide RSS feed
search: true
search_provider: lunr

# Collections
collections:
  products_en:
    output: true
    permalink: /products/:path/
  products_zh:
    output: true
    permalink: /zh/products/:path/

# Site Author
author:
  name: "Berry Palma Shun"
  avatar: /assets/images/bio-photo.jpg # Upload an image to assets/images/
  bio: "专注于光纤连接器和自动化解决方案，提供高质量产品。"
  location: "China"
  email: "berrypalma8@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:berrypalma8@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "[invalid url, do not cite]

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "[invalid url, do not cite]

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/

# Pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false